<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 20.08.2018
 * Time: 20:53
 */

namespace App\Tools;


use App\RedisImitation;
use App\Url;

class UrlGenerator
{
    // could be made with event
    public static function generate(): string
    {
        $possiblePath = RedisImitation::find('autogenerated_path');
        // avoiding situations when new autogenerated path replaces existing custom one
        do {
            $possiblePath['value'] = $possiblePath['value'] + 1;
            $url = Url::where('path', $possiblePath['value'])->first();
        } while ($url !== null);

        $possiblePath->save();
        return $possiblePath['value'];
    }
}